#
# ~/.bashrc
#

export CLICOLOR=1
export SHELL=$(which bash)
export PATH=$HOME/{bin,scripts}:$PATH
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export LESSHISTFILE='-'

# Set vimrc's location and source it on vim startup
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# less timeout when changing modes in vi-mode
export KEYTIMEOUT=1

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

<<<{shconst}
source $HOME/.config/shconst/shaliases
source $HOME/.config/shconst/shenv
>>>{shconst}

# loads inputrc for readline - TODO this line SHOULD be omitted but is required
bind -f ~/.inputrc

# Environmental variables predef
PS1='\w > '
EDITOR=/usr/bin/vim
VISUAL=/usr/bin/vim
