#
# ~/.bash_profile
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

<<<{shconst}
source $HOME/.config/shconst/shaliases
source $HOME/.config/shconst/shenv
>>>{shconst}

# loads inputrc for readline - TODO this line SHOULD be omitted but is required
bind -f ~/.inputrc

# Environmental variables predef
PS1='\e[40m \W \e[0;30m\e[0m '
EDITOR=/usr/bin/vim
VISUAL=/usr/bin/vim
