#!/bin/bash

build() {
    local v="gitconfig"
    build_file $v $HOME/.config/git config
    build_file gitignore $HOME/.config/git gitignore
    project_enabled "ctags"
    local i=$?
    delete_chunk "ctags" ${v} $i
    if [ ${i} -eq 0 ]; then
        build_submodule ctag-hooks
    fi
}
