#! /bin/bash

xset +fp /usr/share/fonts/local
xset fp rehash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f $XDG_CONFIG_HOME/X/Xresources ]] && xrdb -merge $XDG_CONFIG_HOME/X/Xresources
setxkbmap -option caps:super

xcape -e 'Super_L=Escape'

xbindkeys --file $XDG_CONFIG_HOME/X/xbindkeysrc

sxhkd &
urxvt &
exec bspwm
