#!/bin/bash

build() {
    build_file css.config/vim $HOME/.config/vim/after/ftplugin css.config/vim
    build_file c.config/vim $HOME/.config/vim/after/ftplugin c.config/vim
    build_file go.config/vim $HOME/.config/vim/after/ftplugin go.config/vim
    build_file html.config/vim $HOME/.config/vim/after/ftplugin html.config/vim
    build_file java.config/vim $HOME/.config/vim/after/ftplugin java.config/vim
    build_file javascript.config/vim $HOME/.config/vim/after/ftplugin javascript.config/vim
}
