#!/bin/bash

build() {
    path="$HOME/.config/luakit"
    for f in *.lua; do
        build_file $f $path $f
    done
    cp luakit-adblock/adblock.lua .
    cp luakit-adblock/adblock_chrome.lua .
    build_file adblock.lua $path adblock.lua
    build_file adblock_chrome.lua $path adblock_chrome.lua
    rm adblock.lua adblock_chrome.lua
    dot_echo "Downloading adblock filterlist\n"
    curl -O --progress-bar "https://easylist-downloads.adblockplus.org/easylist.txt"
    build_file easylist.txt $path/adblock easylist.txt
    rm easylist.txt
}
