export CLICOLOR=1
export LANG=sv_SE.UTF-8
export LC_CTYPE=$LANG
export SHELL=$(which zsh)
export PATH=$HOME/{bin,scripts}:$PATH
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export LESSHISTFILE='-'

# less timeout when changing modes in vi-mode
export KEYTIMEOUT=1
