#!/usr/bin/bash
out=""
while read -r line; do
   if ! [[ -z $line ]]; then
       head="$(echo $line | head -c 1)"
       if ! [ $head == "\"" ]; then #"
           # out+="${line}"
           echo $line
       fi
   fi
done < $1
echo "${out%?}"
