#!/bin/bash

build() {
    local v="vimrc"
    build_file $v $HOME/.config/vim vimrc
    # delete git specific changes if git is disabled
    project_enabled "git"
    delete_chunk "git" ${v} $?
    project_enabled "ctags"
    delete_chunk "ctags" ${v} $?
    build_submodule ftplugin
    build_submodule colors
}
