#!/bin/bash

build() {
    local v="vimrc"
    build_file $v $HOME/.config/vim vimrc
    # delete git specific changes if git is disabled
    project_enabled "git"
    delete_chunk "git" ${v} $?
    project_enabled "ctags"
    delete_chunk "ctags" ${v} $?
    dot_echo "Minifying vimrc... "
    minify-vim ${build_path}/${v}${FILE_EXT} ${build_path}/${v}${FILE_EXT}
    echo "done"
    build_submodule ftplugin
    build_submodule colors
}
